package com.jct.renthabesha.core.presentation.navigation

sealed class Screen(val route: String) {
    object AddCard : Screen("add_card")
    object AddLocation : Screen("add_location")
    object AddClothing : Screen("add_clothing")
    object AdminDashboard : Screen("admin_dashboard")
    object Checkout : Screen("checkout")
    object ClothingManagement : Screen("clothing_management")
    object CompleteProfile : Screen("complete_profile")
    object EditClothing : Screen("edit_clothing")
    object Home : Screen("home")
    object Landing : Screen("landing")
    object Orders : Screen("orders")
    object Notification : Screen("notification")
    object PasswordManager : Screen("password_manager")
    object PaymentMethods : Screen("payment_methods")
    object PaymentStatus : Screen("payment_status")
    object PrivacyPolicy : Screen("privacy_policy")
    object ProductDetails : Screen("product_details")
    object Profile : Screen("profile")
    object Splash : Screen("splash")
    object Signup : Screen("signup")
    object Signin : Screen("signin")
    object Search : Screen("search")
    object Settings : Screen("settings")
    object ShippingAddress : Screen("shipping_address")
    object UserManagement : Screen("users_management")
    object MyCart: Screen("my_cart")
}